import{useMemo}from'react';import{Background,Controls,MarkerType,ReactFlow,type Edge,type Node}from'@xyflow/react';import type{AgentData,WorkflowEvent,WorkflowStatus}from'../types/workflow';import{AgentNode,type AgentNodeData}from'./AgentNode';
const titles:Record<string,string>={inventory:'Inventory',orders:'Orders',demand:'Demand',supplier:'Supplier',cost_impact:'Cost impact'};const W=152,CANVAS=900;
const nodeTypes={default:AgentNode};
const row=(ids:string[],y:number)=>{const gap=ids.length>1?Math.min(28,(CANVAS-ids.length*W)/(ids.length-1)):0;const width=ids.length*W+(ids.length-1)*gap;return ids.map((id,i)=>({id,x:(CANVAS-width)/2+i*(W+gap),y}))};
export function WorkflowGraph({status,agents,events,onSelect}:{status?:WorkflowStatus;agents:Record<string,AgentData>;events:WorkflowEvent[];onSelect:(x:string)=>void}){const selected=status?.selected_agents||[];const conflict=events.some(x=>x.event==='conflict_detected');const revised=events.some(x=>x.event==='agent_revised');const complete=status?.status==='COMPLETED';const st=(id:string)=>agents[id]?.execution?.status||(id==='data_ingestion'&&status?.data_summary?'COMPLETED':id==='planner'&&selected.length?'COMPLETED':'IDLE');
 const{nodes,edges}=useMemo(()=>{const center=(CANVAS-W)/2;const nodes:Node<AgentNodeData>[]=[{id:'data_ingestion',position:{x:center,y:0},data:{label:'Data ingestion',subtitle:'Excel validation',status:st('data_ingestion')}},{id:'planner',position:{x:center,y:112},data:{label:'Planner agent',subtitle:'Dynamic selection',status:st('planner')}}];row(selected,230).forEach(({id,x,y})=>nodes.push({id,position:{x,y},data:{label:`${titles[id]||id} agent`,subtitle:'Parallel analysis',status:conflict&&!revised&&['supplier','cost_impact'].includes(id)?'REVISION_REQUIRED':st(id)}}));nodes.push({id:'decision',position:{x:center,y:355},data:{label:'Decision agent',subtitle:'Evidence synthesis',status:st('decision')}},{id:'critic',position:{x:center,y:470},data:{label:'Critic agent',subtitle:'Consistency review',status:conflict&&!revised?'CONFLICT':complete?'APPROVED':st('critic'),kind:'critic'}},{id:'action_planner',position:{x:center,y:590},data:{label:'Action planner',subtitle:'Execution roadmap',status:st('action_planner')}},{id:'final',position:{x:center,y:705},data:{label:'Approved plan',subtitle:'Business action',status:complete?'APPROVED':'IDLE',kind:'final'}});if(conflict)nodes.push({id:'revision_router',position:{x:CANVAS-W-8,y:470},data:{label:'Revision router',subtitle:'Targeted correction',status:revised?'COMPLETED':'RUNNING',kind:'router'}});
 const edge=(s:string,t:string,active=true):Edge=>({id:`${s}-${t}`,source:s,target:t,sourceHandle:'bottom',targetHandle:'top',type:'smoothstep',animated:active,markerEnd:{type:MarkerType.ArrowClosed,color:active?'#53e0b5':'#34495a'},style:{stroke:active?'#53e0b5':'#34495a',strokeWidth:1.4}});const edges=[edge('data_ingestion','planner',Boolean(status?.data_summary)),...selected.map(x=>edge('planner',x)),...selected.map(x=>edge(x,'decision',st(x)==='COMPLETED')),edge('decision','critic',Boolean(agents.decision)),edge('critic','action_planner',complete),edge('action_planner','final',complete)];if(conflict){edges.push({...edge('critic','revision_router',!revised),sourceHandle:'right-source',targetHandle:'left-target'});['supplier','cost_impact'].filter(x=>selected.includes(x)).forEach(x=>edges.push({...edge('revision_router',x,!revised),sourceHandle:'left-source',targetHandle:'left-target'}))}return{nodes,edges}},[status,agents,events]);
 const topologyKey=`${selected.join('-')}|${conflict}|${revised}|${complete}`;
 return <section className="glass flex h-full min-w-0 flex-col overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><p className="font-display text-sm font-semibold">Agent workflow</p><p className="text-[11px] text-slate-500">Live, inspectable orchestration</p></div><span className="text-[10px] uppercase tracking-widest text-mint">{selected.length} specialists</span></div><div className="min-h-0 flex-1"><ReactFlow key={topologyKey} colorMode="dark" defaultNodes={nodes} defaultEdges={edges} nodeTypes={nodeTypes} fitView fitViewOptions={{padding:.1}} minZoom={.48} maxZoom={1.3} onNodeClick={(_,n)=>onSelect(n.id)}><Background color="#31495b" gap={24} size={1}/><Controls showInteractive={false}/></ReactFlow></div></section>}
